### ISSUE TITLE
source code release

### ISSUE THREAD

**Issue by Xbbei** [xuchen-ethz/gdna#1]
Hi, chenxu:

My name is xubaobei, Recently, i read your cvpr2022 paper gDNA. It is a great job. I look forward to try it. So when do you release the source code of gNDA?

Best Wishes!
Baobei Xu

**Comment by xuchen-ethz** [comment]
Hi Baobei,

Thank you for your interest in our work :) We will release the code by the end of May.

Best
Xu

**Comment by PeterouZh** [comment]
Looking forward to the code.

**Comment by xuchen-ethz** [comment]
I am sorry that we are behind our original schedule... We are still working on cleaning up the code and should finish it next week. Sorry for the inconvenience and stay tuned!

**Comment by PeterouZh** [comment]
Looking forward to the code again:)

**Comment by junzhezhang** [comment]
Looking forward to the code as well :-)

**Comment by xuchen-ethz** [comment]
I am so sorry for the 2x delay. The code is finally here. We also include an additional model that is trained on a free dataset THuman2.0 - hope this makes the code, especially the training part, easier to use. 

let me know if there is any question. Again, I am very sorry for the delay, and thank you so much for your patience!
